### PR TITLE
Bounty - Pip installations

### PR DESCRIPTION
**Pull request by SalehAhmad1**
I have setup pip installations for all packages.

**Things to note:**
1. Packages being shared/used by one or more modalities were set as required packages like:
- sounddevice
- librosa
- torch
- transformers
- torchaudio
etc

2. Packages being used by the TTS/LLM/TTS have been setup as individual installations.
i.e. OpenVoiceChat[piper], OpenVoiceChat[xtts], OpenVoiceChat[llama] etc etc

I have also updated the Readme.md for better understanding of the user.

### CODE REVIEW

**Comment by fakhirali** [comment]
pip installing individual libs works. 

I cannot do 
```python 
import OpenVoiceChat as ovc
```
but the following works:
```python
import llm.llm_gpt as llm_gpt
```
Maybe putting all of the things into an OpenVoiceChat module works? Idk. 
Ideally it is like the following:
```python
import OpenVoiceChat as ovc
from ovc.llm import llm_gpt
```

**Comment by SalehAhmad1** [comment]
Ok, I will update it then we'll test again.

**Comment by SalehAhmad1** [comment]
Damnn, I didn't know it updates in the same PR without me sending one again xD

**Comment by fakhirali** [comment]
Ez scene bro. Just commit to this branch aur PR updates.

**Comment by SalehAhmad1** [comment]
OVC can now be installed by using 
- pip install -e git+https://github.com/SalehAhmad1/OpenVoiceChat.git#egg=OpenVoiceChat
or 
- pip install -e git+https://github.com/SalehAhmad1/OpenVoiceChat.git#egg=OpenVoiceChat[piper]
etc etc

Important Points:
- All subpackages (llm, stt, tts) are included, and usable. 
- When a user initializes a chat bot let's say Chatbot_GPT in this case, a warning will be raised if openai is not installed. else it won't. Same goes for all optional requirements.

**Comment by fakhirali** [comment]
Could you add transformers as an additional dependency as well. And also do the imports in init with llm_hf.
Bounty Completed! :moneybag:

**Comment by SalehAhmad1** [comment]
> Could you add transformers as an additional dependency as well. And also do the imports in init with llm_hf. I also feel torch is a heavy lib. When do we need it, can we remove it since transformers already requires it? Also we are probably version 0.1 lol
> 
> Bounty Completed! 💰

Files like main.py, translation.py etc import torch and use to setup compute device.

I'll add transformers as an optional dependency too, and edit the version too.

**Comment by fakhirali** [comment]
Hmm then leave torch in for now.

**Pull request merged**
